# Generated by Django 4.1.5 on 2023-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=15)),
                ('Laat_Name', models.CharField(max_length=50)),
                ('Phone_NO', models.BigIntegerField()),
                ('Joining_Date', models.DateField()),
                ('Designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
