# Generated by Django 4.1.5 on 2023-02-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Laat_Name',
            new_name='Last_Name',
        ),
    ]
