# Generated by Django 4.1.5 on 2023-02-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_laat_name_employees_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='salary',
            new_name='Salary',
        ),
    ]
