# Generated by Django 4.1.5 on 2023-02-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_salary_salary_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salary',
            new_name='department',
        ),
    ]
