# Generated by Django 4.1.5 on 2023-02-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Subject', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.IntegerField()),
                ('Description', models.TextField(max_length=100)),
            ],
        ),
    ]
